apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-recommender-deployment
  labels:
    app: movie-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-recommender
  template:
    metadata:
      labels:
        app: movie-recommender
    spec:
      containers:
        - name: movie-recommender-container
          # 🔹 Use the image you pushed to Docker Hub
          image: narlarushikesh/movie-recommender:latest
          # 🔹 Always pull from Docker Hub to avoid stale caches
          imagePullPolicy: Always

          # 🔹 Streamlit port
          ports:
            - containerPort: 8501

          # 🔹 Pass Splunk variables as environment values
          env:
            - name: SPLUNK_HEC_URL
              value: "http://splunk-service:8088"
            - name: SPLUNK_TOKEN
              value: "4fc0fc47-2d1c-4039-8986-e554bb1f9008"
            - name: SPLUNK_INDEX
              value: "main"

          # 🔹 Resource requests and limits
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          # 🔹  simple readiness probe to confirm app started
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 15
            periodSeconds: 10

          # 🔹 liveness probe for restarts on failure
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 20
